apiVersion: v1
kind: ConfigMap
metadata:
  name: my-html-config
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>My K8s App</title>
    </head>
    <body>
        <h1>Hello from Kubernetes with GitHub Actions!</h1>
    </body>
    </html>
