name: Deploy to Kubernetes

on:
  push:
    branches:
      - main
  workflow_dispatch: 

jobs:
  deploy:
    runs-on: self-hosted  # your Windows runner label

    steps:
      - name: Apply Kubernetes manifests
        run: kubectl apply -f k8s-manifests/

       # shell: powershell
